### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by VegasChickiChicki** [storybook-vue/storybook-nuxt#38]
PS C:\Users\dodaa\WebstormProjects\popso> npm run storybook

> nuxt-app@1.0.10 storybook
> storybook dev -p 6006

@storybook/cli v7.3.0

WARN   Failed to load preset: "@storybook-vue\\nuxt\\preset"
ERR! C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook-vue\nuxt\dist\preset.mjs:1
ERR! import { resolve, join } from 'path';
ERR! ^^^^^^
ERR! 
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader [as .mjs] (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook-vue\nuxt\preset.js:1:18)
ERR!  C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook-vue\nuxt\dist\preset.mjs:1
ERR! import { resolve, join } from 'path';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader [as .mjs] (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook-vue\nuxt\preset.js:1:18)
WARN   Failed to load preset: {"type":"presets","name":"C:\\Users\\dodaa\\WebstormProjects\\popso\\node_modules\\storybook-addon-nuxt\\dist\\preset.js"} on level 1
ERR! C:\Users\dodaa\WebstormProjects\popso\node_modules\storybook-addon-nuxt\dist\preset.js:1
ERR! import { fileURLToPath } from 'node:url';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Object.extensions..js (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!  C:\Users\dodaa\WebstormProjects\popso\node_modules\storybook-addon-nuxt\dist\preset.js:1
ERR! import { fileURLToPath } from 'node:url';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Object.extensions..js (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR! Error: Invariant failed: No builder configured in core.builder
ERR!     at invariant (C:\Users\dodaa\WebstormProjects\popso\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
ERR!     at buildDevStandalone (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\core-server\dist\index.js:128:1790)
ERR!     at async withTelemetry (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\core-server\dist\index.js:113:3910)
ERR!     at async dev (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\cli\dist\generate.js:457:401)
ERR!     at async Command.<anonymous> (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\cli\dist\generate.js:459:225)
ERR!  Error: Invariant failed: No builder configured in core.builder
ERR!     at invariant (C:\Users\dodaa\WebstormProjects\popso\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
ERR!     at buildDevStandalone (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\core-server\dist\index.js:128:1790)
ERR!     at async withTelemetry (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\core-server\dist\index.js:113:3910)
ERR!     at async dev (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\cli\dist\generate.js:457:401)
ERR!     at async Command.<anonymous> (C:\Users\dodaa\WebstormProjects\popso\node_modules\@storybook\cli\dist\generate.js:459:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN   Failed to load preset: {"type":"presets","name":"C:\\Users\\dodaa\\WebstormProjects\\popso\\node_modules\\storybook-addon-nuxt\\dist\\preset.js"} on level 1
ERR! C:\Users\dodaa\WebstormProjects\popso\node_modules\storybook-addon-nuxt\dist\preset.js:1
ERR! import { fileURLToPath } from 'node:url';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Object.extensions..js (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!  C:\Users\dodaa\WebstormProjects\popso\node_modules\storybook-addon-nuxt\dist\preset.js:1
ERR! import { fileURLToPath } from 'node:url';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
ERR!     at Object.newLoader (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at Object.extensions..js (C:\Users\dodaa\WebstormProjects\popso\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1033:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1057:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)

storybook config(main.js):

```
import { mergeConfig } from 'vite'
import userConfig from './vite.config';

module.exports = {
  stories: [
    '../components/**/*.docs.mdx',
    '../components/**/*.stories.@(js|ts)',
    '../pages/**/*.stories.@(js|ts)'
  ],
  addons: [
    '@storybook/addon-essentials',
    'storybook-addon-nuxt'
  ],
  framework: {
    name: '@storybook-vue/nuxt',
    options: {}
  },
  docs: {
    autodocs: 'tag'
  },
  async viteFinal(baseConfig) {
    return mergeConfig(baseConfig, userConfig);
  }
};
```

userConfig:

```
import { fileURLToPath } from 'url';
import { defineConfig } from 'vite';

export default defineConfig({
	resolve: {
		alias: {
			'~': fileURLToPath(new URL('../', import.meta.url)),
			'@': fileURLToPath(new URL('../', import.meta.url)),
		},
	},
	css: {
		preprocessorOptions: {
			scss: {
				additionalData: `
					@import "@/assets/styles/variables/colors.scss";
					@import "@/assets/styles/variables/media.scss";
					@import "@/assets/styles/mixins/layouts.scss";
					@import "@/assets/styles/mixins/media.scss";
					@import "@/assets/styles/mixins/typography.scss";
					@import "@/assets/styles/mixins/helpers.scss";
				`
			}
		}
	}
});
```

**Comment by chakAs3** [comment]
@VegasChickiChicki , let me check this, i'm releasing  a new version today. i would like you to test it.

**Comment by happy-turtle** [comment]
Same as described [here](https://github.com/storybook-vue/storybook-nuxt-demo/issues/6). The current path resolution does not work on Windows but only on Linux.

**Comment by VegasChickiChicki** [comment]
> @VegasChickiChicki , let me check this, i'm releasing a new version today. i would like you to test it.

Errors is gone. Can close issue, i think. 
Thank you so much for your work! Storybook is very important for my project!
