### ISSUE TITLE
On install: SB_CORE-COMMON_0003

### ISSUE THREAD

**Issue by lalvarezweb** [storybook-vue/storybook-nuxt#56]
Error after using npx storybook-nuxt init

@storybook/cli v7.4.0

SB_CORE-COMMON_0003: Could not evaluate the '@storybook-vue/nuxt' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
    at validateFrameworkName (.\node_modules\@storybook\core-common\dist\index.js:52:4385)
    at buildDevStandalone (.\node_modules\@storybook\cli\node_modules\@storybook\core-server\dist\index.js:116:1467)
    at async withTelemetry (.\node_modules\@storybook\cli\node_modules\@storybook\core-server\dist\index.js:101:4155)
    at async dev (.\node_modules\@storybook\cli\dist\generate.js:502:401)
    at async Command.<anonymous> (.\node_modules\@storybook\cli\dist\generate.js:504:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Comment by chakAs3** [comment]
@lalvarezweb  i published new version cli, simpler please use it

`npx storybook-nuxt@0.0.5-alpha.2 init`

**Comment by lalvarezweb** [comment]
> @lalvarezweb i published new version cli, simpler please use it
> 
> `npx storybook-nuxt@0.0.5-alpha.2 init`

![image](https://github.com/storybook-vue/storybook-nuxt/assets/124052210/86602b9c-e855-43c1-9557-ec79cae98718)

**Comment by chakAs3** [comment]
@lalvarezweb  please try. again. `npx storybook-nuxt@0.0.5-alpha.3 init` i pushed a fix

**Comment by chakAs3** [comment]
can you run this command `npm install storybook@next @storybook-vue/nuxt --save-dev`

**Comment by lalvarezweb** [comment]
> 

It did not generate me any script in the package.json, I added this line to try to run storybook:
""storybook": "storybook dev -p 6006".

It returns the following error:
![image](https://github.com/storybook-vue/storybook-nuxt/assets/124052210/bad3b90a-a2b2-4e20-a305-94d20bc35dd6)

**Comment by flabbert** [comment]
I have the same issue, 

started a brand new nuxt project with `npx nuxi@latest init` 

and then do `npx storybook-nuxt init`

I get  
`SB_CORE-COMMON_0003: Could not evaluate the '@storybook-vue/nuxt' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
    at validateFrameworkName (.\node_modules\@storybook\core-common\dist\index.js:52:4385)
    at buildDevStandalone (.\node_modules\@storybook\core-server\dist\index.js:116:1467)
    at async withTelemetry (.\node_modules\@storybook\core-server\dist\index.js:101:4155)
    at async dev (.\node_modules\@storybook\cli\dist\generate.js:502:401)
    at async Command.<anonymous> (.\node_modules\@storybook\cli\dist\generate.js:504:225)`

no difference if i use npm, pnpm or yarn

**Comment by chakAs3** [comment]
> I have the same issue,
> 
> started a brand new nuxt project with `npx nuxi@latest init`
> 
> and then do `npx storybook-nuxt init`
> 
> I get
> 
> ```
> SB_CORE-COMMON_0003: Could not evaluate the '@storybook-vue/nuxt' package from the 'framework' field of Storybook config.
> 
> Are you sure it's a valid package and is installed?
>     at validateFrameworkName (.\node_modules\@storybook\core-common\dist\index.js:52:4385)
>     at buildDevStandalone (.\node_modules\@storybook\core-server\dist\index.js:116:1467)
>     at async withTelemetry (.\node_modules\@storybook\core-server\dist\index.js:101:4155)
>     at async dev (.\node_modules\@storybook\cli\dist\generate.js:502:401)
>     at async Command.<anonymous> (.\node_modules\@storybook\cli\dist\generate.js:504:225)
> ```
> 
> no difference if i use npm, pnpm or yarn

it is because of some breakinng changes in storybook dev im working on it

**Comment by lalvarezweb** [comment]
let us know to try

**Comment by h7ml** [comment]
I also encountered this issue when using modern.js integration storybook, and the message log is as follows:
```bash
> calendar@0.1.0 storybook \calendar
> storybook dev -p 6006

@storybook/cli v7.6.17

(node:23596) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '@modern-js/storybook' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
    at validateFrameworkName (.\node_modules\.pnpm\@storybook+core-common@7.6.17\node_modules\@storybook\core-common\dist\index.js:21:4479)
    at buildDevStandalone (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:119:1432)
    at async withTelemetry (.\node_modules\.pnpm\@storybook+core-server@7.6.17\node_modules\@storybook\core-server\dist\index.js:65:3948)
    at async dev (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:514:401)
    at async Command.<anonymous> (.\node_modules\.pnpm\@storybook+cli@7.6.17\node_modules\@storybook\cli\dist\generate.js:529:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

 ELIFECYCLE  Command failed with exit code 1.
```

I see above there is also an error log for `SB_CORE-COMMON_0003`, so is this a storybook problem?

**Comment by jaduranidavalos-ms** [comment]
is there any update to this? i'm getting this error on storybook 8

```
@storybook/core v8.4.2

The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '@storybook-vue/nuxt' package from the 'framework' field of Storybook config.

Are you sure it's a valid package and is installed?
```

**Comment by h7ml** [comment]
> is there any update to this? i'm getting this error on storybook 8
> 
> ```
> @storybook/core v8.4.2
> 
> The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
> SB_CORE-COMMON_0003 (CouldNotEvaluateFrameworkError): Could not evaluate the '@storybook-vue/nuxt' package from the 'framework' field of Storybook config.
> 
> Are you sure it's a valid package and is installed?
> ```

windows ?

**Comment by jaduranidavalos-ms** [comment]
@h7ml  Apple M3
